"""credentials table

Revision ID: bae7b516d141
Revises: 
Create Date: 2022-08-04 06:50:42.186372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae7b516d141'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_username'), 'credentials', ['username'], unique=True)
    op.create_table('studentdetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student', sa.String(length=64), nullable=True),
    sa.Column('course', sa.String(length=64), nullable=True),
    sa.Column('fee', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('grades', sa.String(length=128), nullable=True),
    sa.Column('contact', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studentdetails_course'), 'studentdetails', ['course'], unique=False)
    op.create_index(op.f('ix_studentdetails_student'), 'studentdetails', ['student'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studentdetails_student'), table_name='studentdetails')
    op.drop_index(op.f('ix_studentdetails_course'), table_name='studentdetails')
    op.drop_table('studentdetails')
    op.drop_index(op.f('ix_credentials_username'), table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###
